# Generated by Django 6.0.6 on 2026-06-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontogram', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toothtreatment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatments.treatment'),
        ),
        migrations.AlterUniqueTogether(
            name='tooth',
            unique_together={('odontogram', 'number')},
        ),
    ]
