# Generated by Django 6.0.6 on 2026-06-22 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_title', models.CharField(max_length=64)),
                ('host', models.CharField(max_length=128)),
                ('port', models.PositiveIntegerField()),
                ('transfer_syntax', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='imaging/')),
                ('file_type', models.CharField(max_length=64)),
                ('study_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='imaging/thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.PositiveIntegerField()),
                ('modality', models.CharField(max_length=64)),
                ('body_part', models.CharField(blank=True, max_length=64)),
                ('laterality', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='imaging.imaginginstance')),
            ],
        ),
        migrations.AddField(
            model_name='imaginginstance',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='imaging.imagingseries'),
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_type', models.CharField(max_length=64)),
                ('study_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=32)),
                ('source_system', models.CharField(blank=True, max_length=128)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='imagingseries',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='imaging.imagingstudy'),
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_text', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='imaging.imagingstudy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
