# Generated by Django 6.1.1 on 2026-09-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoice_lines', to='billing.prestation'),
        ),
    ]
