# Generated by Django 6.1.1 on 2026-09-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('practitioner', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['practitioner', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['practitioner', 'weekday', 'is_active'], name='website_wor_practit_729dfc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='working_hours_end_after_start'), models.UniqueConstraint(fields=('practitioner', 'weekday', 'start_time', 'end_time'), name='unique_practitioner_working_hours')],
            },
        ),
    ]
