# Generated by Django 6.1.1 on 2026-09-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='appointments.appointment'),
        ),
    ]
