# Generated by Django 6.1.1 on 2026-09-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_treatment_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='total_price',
        ),
    ]
