# Generated by Django 6.1.1 on 2026-10-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_remove_treatment_price_remove_treatment_tax_rate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='treatment',
            name='treatments__status_ddde78_idx',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='status',
        ),
    ]
