# Generated by Django 6.1.2 on 2026-10-09 20:26

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='generated_docx',
            field=models.FileField(blank=True, storage=documents.storage.PrivateDocumentStorage(), upload_to='generated_prescriptions/'),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='docx_file',
            field=models.FileField(blank=True, storage=documents.storage.PrivateDocumentStorage(), upload_to='prescription_templates/'),
        ),
    ]
