# Generated by Django 6.0.6 on 2026-06-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment_plans', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplanitem',
            name='treatment_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatments.treatmenttemplate'),
        ),
        migrations.AddField(
            model_name='treatmentplanstage',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='treatment_plans.treatmentplan'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treatment_plans.treatmentplanstage'),
        ),
    ]
